export const SUBMIT_LICENSE_SUCCESS = "SUBMIT_LICENSE_SUCCESS";
export const SUBMIT_LICENSE_FAIL = "SUBMIT_LICENSE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
