export const BUSINESS_REGISTRATION_SUCCESS = "BUSINESS_REGISTRATION_SUCCESS";
export const BUSINESS_REGISTRATION_FAIL = "BUSINESS_REGISTRATION_FAIL";
export const BUSINESS_VERIFICATION_SUCCESS = "BUSINESS_VERIFICATION_SUCCESS";
export const BUSINESS_VERIFICATION_FAIL = "BUSINESS_VERIFICATION_FAIL";
export const REVERIFY_BUSINESS_SUCCESS = "REVERIFY_BUSINESS_SUCCESS";
export const REVERIFY_BUSINESS_FAIL = "REVERIFY_BUSINESS_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";