export const REGISTER_VEHICLE_SUCCESS = "REGISTER_VEHICLE_SUCCESS";
export const REGISTER_VEHICLE_FAIL = "REGISTER_VEHICLE_FAIL";
export const UPDATE_VEHICLE_SUCCESS = "UPDATE_VEHICLE_SUCCESS";
export const UPDATE_VEHICLE_FAIL = "UPDATE_VEHICLE_FAIL";
export const DELETE_VEHICLE = "DELETE_VEHICLE";


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";