export const ADD_FUNDS_SUCCESS = "ADD_FUNDS_SUCCESS";
export const ADD_FUNDS_FAIL = "ADD_FUNDS_FAIL";
export const WITHDRAW_FUNDS_SUCCESS = "WITHDRAW_FUNDS_SUCCESS";
export const WITHDRAW_FUNDS_FAIL = "WITHDRAW_FUNDS_FAIL";
// export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
// export const GET_BALANCE_FAIL = "GET_BALANCE_FAIL";
// export const GET_EARNINGS_SUCCESS = "GET_EARNINGS_SUCCESS";
// export const GET_EARNINGS_FAIL = "GET_EARNINGS_FAIL";
// export const GET_DEPOSITS_SUCCESS = "GET_DEPOSITS_SUCCESS";
// export const GET_DEPOSITS_FAIL = "GET_DEPOSITS_FAIL";
// export const GET_WITHDRAWALS_SUCCESS = "GET_WITHDRAWALS_SUCCESS";
// export const GET_WITHDRAWALS_FAIL = "GET_WITHDRAWALS_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";