export const GET_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
