export const CREATEPARCEL_SUCCESS = "CREATEPARCEL_SUCCESS";
export const CREATEPARCEL_FAIL = "CREATEPARCEL_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";